# Do NOT update manually; changes here will be overwritten by Copier
_commit: 5a39237
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_real_version: 12.0
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: '

    ## Authors

    * La Jardinière

    * GRAP (https://www.grap.coop/)

    ## Contributors

    * Sylvain LE GAL <https://twitter.com/legalsylvain>


    ## Funders

    The development of this module has been financially supported by:

    * La Région Auvergne Rhône-Alpes

    ![La Région Auvergne Rhône-Alpes](./static/logo_region_auvergne_rhone_alpes.png)

    '
repo_name: Main repository for GRAP Logistics modules
repo_slug: odoo-addons-logistics
repo_website: https://github.com/grap/odoo-addons-logistics
travis_apt_packages: []
travis_apt_sources: []

