from . import joint_buying_check_access_mixin
from . import joint_buying_mixin
from . import res_company
from . import res_partner
from . import res_partner_category
from . import res_users
from . import res_config_settings
from . import joint_buying_tour
from . import joint_buying_tour_line
