from . import product_product
from . import product_template
from . import product_supplier_info
from . import res_company
from . import res_partner
from . import res_users
from . import joint_buying_purchase_order_grouped
from . import joint_buying_purchase_order_grouped_line
from . import joint_buying_purchase_order
from . import joint_buying_purchase_order_line
from . import res_config_settings
